package inks

import org.openrndr.color.ColorRGBa
import org.openrndr.color.rgb

class RisoInk(val name: String, val color: ColorRGBa)

object Riso {
    val BLACK = RisoInk("black", rgb("000000"))
    val BURGUNDY = RisoInk("burgundy", rgb("914E72"))
    val BLUE = RisoInk("blue", rgb("0078BF"))
    val GREEN = RisoInk("green", rgb("00A95C"))
    val MEDIUM_BLUE = RisoInk("medium blue", rgb("3255A4"))
    val BRIGHT_RED = RisoInk("bright red", rgb("F15060"))
    val FEDERAL_BLUE = RisoInk("federal blue", rgb("3D5588"))
    val PURPLE = RisoInk("purple", rgb("765BA7"))
    val TEAL = RisoInk("teal", rgb("00838A"))
    val FLAT_GOLD = RisoInk("flat gold", rgb("BB8B41"))
    val HUNTER_GREEN = RisoInk("hunter green", rgb("407060"))
    val RED = RisoInk("red", rgb("FF665E"))
    val BROWN = RisoInk("brown", rgb("925F52"))
    val YELLOW = RisoInk("yellow", rgb("FFE800"))
    val MARINE_RED = RisoInk("marine red", rgb("D2515E"))
    val ORANGE = RisoInk("orange", rgb("FF6C2F"))
    val FLUORESCENT_PINK = RisoInk("fluorescent pink", rgb("FF48B0"))
    val LIGHT_GRAY = RisoInk("light gray", rgb("88898A"))
    val METALLIC_GOLD = RisoInk("metallic gold", rgb("AC936E"))
    val CRIMSON = RisoInk("crimson", rgb("E45D50"))
    val FLUORESCENT_ORANGE = RisoInk("fluorescent orange",rgb("FF7477"))
    val CORNFLOWER = RisoInk("cornflower", rgb("62A8E5"))
    val SKY_BLUE = RisoInk("sky blue", rgb("4982CF"))
    val SEA_BLUE = RisoInk("sea blue", rgb("0074A2"))
    val LAKE = RisoInk("lake", rgb("235BA8"))
    val INDIGO = RisoInk("indigo",rgb("484D7A"))
    val MIDNIGHT = RisoInk("midnight", rgb("435060"))
    val MIST = RisoInk("mist", rgb("B8C7C4"))
    val GRANITE = RisoInk("granite", rgb("A5AAA8"))
    val CHARCOAL = RisoInk("charcoal", rgb("70747C"))
    val SMOKY_TEAL = RisoInk("smoky teal", rgb("5F8289"))
    val STEEL = RisoInk("steel", rgb("375E77"))
    val SLATE = RisoInk("slate", rgb("5E695E"))
    val TURQUOISE = RisoInk("turquoise", rgb("00AA93"))
    val EMERALD = RisoInk("emerald", rgb("19975D"))
    val GRASS = RisoInk("grass", rgb("397E58"))
    val FOREST = RisoInk("forest", rgb("516E5A"))
    val SPRUCE = RisoInk("spruce", rgb("4A635D"))
    val MOSS = RisoInk("moss", rgb("68724D"))
    val SEAFOAM = RisoInk("sea foam", rgb("62C2B1"))
    val KELLY_GREEN = RisoInk("kelly green", rgb("67B346"))
    val LIGHT_TEAL = RisoInk("light teal", rgb("009DA5"))
    val IVY = RisoInk("ivy", rgb("169B62"))
    val PINE = RisoInk("pine", rgb("237E74"))
    val LAGOON = RisoInk("lagoon", rgb("2F6165"))
    val VIOLET = RisoInk("violet", rgb("9D7AD2"))
    val ORCHID = RisoInk("orchid", rgb("BB76CF"))
    val PLUM = RisoInk("plum", rgb("845991"))
    val RAISIN = RisoInk("raisin", rgb("775D7A"))
    val GRAPE = RisoInk("grape", rgb("6C5D80"))
    val SCARLET = RisoInk("scarlet", rgb("F65058"))
    val TOMATO = RisoInk("tomato", rgb("D2515E"))
    val CRANBERRY = RisoInk("cranberry", rgb("C24F5D"))
    val MAROON = RisoInk("maroon", rgb("9E4C6E"))
    val RASPBERRY_RED = RisoInk("raspberry red", rgb("B44B65"))
    val BRICK = RisoInk("brick", rgb("A75154"))
    val LIGHT_LIME = RisoInk("light lime", rgb("E3ED55"))
    val SUNFLOWER = RisoInk("sunflower", rgb("FFB511"))
    val MELON = RisoInk("melon", rgb("FFAE3B"))
    val APRICOT = RisoInk("apricot", rgb("F6A04D"))
    val PAPRIKA = RisoInk("paprika", rgb("EE7F4B"))
    val PUMPKIN = RisoInk("pumpkin", rgb("FF6F4C"))
    val BRIGHT_OLIVE_GREEN = RisoInk("bright olive green", rgb("B49F29"))
    val BRIGHT_GOLD = RisoInk("bright gold", rgb("BA8032"))
    val COPPER = RisoInk("copper", rgb("BD6439"))
    val MAHOGANY = RisoInk("mahogany", rgb("8E595A"))
    val BISQUE = RisoInk("bisque", rgb("F2CDCF"))
    val BUBBLE_GUM = RisoInk("bubble gum", rgb("F984CA"))
    val LIGHT_MUAVE = RisoInk("light muave", rgb("E6B5C9"))
    val DARK_MUAVE = RisoInk("dark muave", rgb("BD8CA6"))
    val WINE = RisoInk("wine", rgb("914E72"))
    val GRAY = RisoInk("gray", rgb("928D88"))
}